### ISSUE TITLE
Patrace build issue:Makefile:23: recipe for target 'callNdkBuild' failed

### ISSUE THREAD

**Issue by goodwelldj** [ARM-software/patrace#5]
ant release
Buildfile: /home/user/work/git/patrace/patrace/project/android/eglretrace/build.xml

-set-mode-check:

-set-release-mode:
     [echo] *************************************************
     [echo] ****  Android Manifest has debuggable=true   ****
     [echo] **** Doing DEBUG packaging with RELEASE keys ****
     [echo] *************************************************

-release-obfuscation-check:
     [echo] proguard.config is ${proguard.config}

-pre-build:

-check-env:
 [checkenv] Android SDK Tools Revision 23.0.2
 [checkenv] Installed at /home/user/work/android/adt-bundle-linux-x86_64-20140702/sdk

-setup:
     [echo] Project Name: eglretrace
  [gettype] Project Type: Application

-build-setup:
[getbuildtools] Using latest Build Tools: 20.0.0
     [echo] Resolving Build Target for eglretrace...
[gettarget] Project Target:   Android 6.0
[gettarget] API level:        23
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: /home/user/work/git/patrace/patrace/project/android/eglretrace/bin
    [mkdir] Created dir: /home/user/work/git/patrace/patrace/project/android/eglretrace/bin/res
    [mkdir] Created dir: /home/user/work/git/patrace/patrace/project/android/eglretrace/bin/rsObj
    [mkdir] Created dir: /home/user/work/git/patrace/patrace/project/android/eglretrace/bin/rsLibs
    [mkdir] Created dir: /home/user/work/git/patrace/patrace/project/android/eglretrace/gen
    [mkdir] Created dir: /home/user/work/git/patrace/patrace/project/android/eglretrace/bin/classes
    [mkdir] Created dir: /home/user/work/git/patrace/patrace/project/android/eglretrace/bin/dexedLibs
     [echo] ----------
     [echo] Resolving Dependencies for eglretrace...
[dependency] Library dependencies:
[dependency] No Libraries
[dependency] 
[dependency] ------------------
     [echo] ----------
     [echo] Building Libraries with 'release'...
   [subant] No sub-builds to iterate on

-code-gen:
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Generating resource IDs...

BUILD FAILED
/home/user/work/android/adt-bundle-linux-x86_64-20140702/sdk/tools/ant/build.xml:653: The following error occurred while executing this line:
/home/user/work/android/adt-bundle-linux-x86_64-20140702/sdk/tools/ant/build.xml:698: Execute failed: java.io.IOException: Cannot run program "/home/user/work/android/adt-bundle-linux-x86_64-20140702/sdk/build-tools/android-4.4W/aapt" (in directory "/home/user/work/git/patrace/patrace/project/android/eglretrace"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
	at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:424)
	at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:438)
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:630)
	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:669)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:497)
	at com.android.ant.AaptExecTask.execute(AaptExecTask.java:699)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at java.util.Vector.forEach(Vector.java:1275)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
	at com.android.ant.IfElseTask.execute(IfElseTask.java:120)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at java.util.Vector.forEach(Vector.java:1275)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:391)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1388)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1361)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.Main.runBuild(Main.java:834)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 48 more

Total time: 1 second
Makefile:23: recipe for target 'callNdkBuild' failed
make: *** [callNdkBuild] Error 1
make: Leaving directory '/home/user/work/git/patrace/patrace/project/android/eglretrace'
The following command failed with error code 2:
make -j8 -C /home/user/work/git/patrace/scripts/../patrace/project/android/eglretrace

**Comment by per-mathisen-arm** [comment]
Hi, that's a bit weird, as we don't really reference aapt anywhere in our build system. Can you try the solutions presented here: https://stackoverflow.com/questions/22701405/aapt-ioexception-error-2-no-such-file-or-directory-why-cant-i-build-my-grad ? Thanks.

**Comment by goodwelldj** [comment]
It worked after I executed "sudo apt-get install lib32stdc++6 lib32z1"

Thanks
